### ISSUE TITLE
Admin - Alertas

### ISSUE THREAD

**Issue by castromaciel** [Lauty10/FrondFinal#19]
## Proceso

1. Iniciar sesión como Admin.
2. Editar un usuario y editar un producto.
3. No modificar ningún dato.
4. Enviar la confirmación

## Resultado esperado

Se esperaba que al editar usuarios y productos sin modificar la información existente, no genere la alerta sobre la modificación de producto actualizado.

En caso de modificar al usuario, correspondería la modificación del texto de alerta para quien lo recibe.

## Resultado actual

Actualmente si editamos usuarios y productos sin modificarlos, se genera la alerta de productos actualizados.

## Captura

![image](https://github.com/Lauty10/FrondFinal/assets/83432755/3856c2fc-15a5-4970-9e94-7c29491a7a9d)

![image](https://github.com/Lauty10/FrondFinal/assets/83432755/16510bb8-91bf-4ae0-8cf4-7976a9ca8c83)

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by Lauty10** [comment]
https://github.com/Lauty10/FullRock/commit/095147849d3c7676c3785edf9ee13a4a10cff714

**Comment by castromaciel** [comment]
Buenas @Lauty10 Quedan pendientes todos los tipo `alert`, lo ideal es no utilizar el alert nativo de js, si no usar un modal visualmente mas agradable. Puedes utilizar Sweet Alert.

<img width="883" alt="image" src="https://github.com/Lauty10/FrondFinal/assets/83432755/85eb117d-d3ec-4d8a-9b35-d20f2deb5811">

<img width="308" alt="image" src="https://github.com/Lauty10/FrondFinal/assets/83432755/912a7fa6-7f34-41e8-881c-0d90dc14babb">

**Comment by Lauty10** [comment]
https://github.com/Lauty10/FrondFinal/commit/9c4f82b015a74acc9aab26ef3dfd260cf9b67a23

**Comment by castromaciel** [comment]
https://github.com/Lauty10/FrondFinal/commit/9c4f82b015a74acc9aab26ef3dfd260cf9b67a23#r139745878

Tener en cuenta lo comentado
