### ISSUE TITLE
Logo en el footer

### ISSUE THREAD

**Issue by castromaciel** [Lauty10/FrondFinal#20]
## Proceso

1. Navegar hacia el footer.
2. Click al logo representativo de la web.

## Resultado esperado

Se esperaba que al darle click a al logo, este redirija al usuario hasta la página de inicio o en su defecto, redirigir a la página de error.

## Resultado actual

Actualmente al intentar clickearlo no cumple ninguna función.

## Captura

https://github.com/Lauty10/FrondFinal/assets/83432755/2b2b45b7-ffca-4c3a-a975-9b9f77b10aa1

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by Lauty10** [comment]
https://github.com/Lauty10/FrondFinal/commit/cd459a81bf40b4662a8d78cceb6f13257e860d27

**Comment by castromaciel** [comment]
Si bien, ahora redirige a una pagina de error, lo ideal es que:

- Los logos redirijan al inicio o al tope de la página actual.
- La página de error sea una propia, no la de vercel
- Hay un error en cuanto a la configuracion de enrutamiento/redirecciones.



https://github.com/Lauty10/FrondFinal/assets/83432755/88b5c2dc-5658-42de-bc2f-b02fe6cc9b2f

**Comment by Lauty10** [comment]
https://github.com/Lauty10/FrondFinal/commit/ad7141eaa3345fe5045207813ec5cac77e01e58c

**Comment by castromaciel** [comment]
Se valida la solución!
