### ISSUE TITLE
Logo navbar

### ISSUE THREAD

**Issue by castromaciel** [Lauty10/FrondFinal#21]
## Proceso

1. Página de inicio.
2. Dirigirse a las secciones: INICIAR SESIÓN y REGISTRARSE.
3. Click en el logo del navbar.

## Resultado esperado

Se esperaba que en ambas secciones, al clickear el logo del navbar, este redirija al usuario hasta la página de inicio.

## Resultado actual

Actualmente no tiene función, pero modifica el link.

## Captura

https://github.com/Lauty10/FrondFinal/assets/83432755/131e3399-807b-49df-ac5b-52b11e2145b3

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by Lauty10** [comment]
https://github.com/Lauty10/FrondFinal/commit/07230d391d6b1fa667a01b1f3a73b29d8382422b

**Comment by castromaciel** [comment]
Se valida la solución del issue!
