### ISSUE TITLE
Eliminar los console.log

### ISSUE THREAD

**Issue by castromaciel** [Lauty10/FrondFinal#23]
Actualmente se presentan los errores de consola en la navegación por páginas, como las de inicio, sobre mi, iniciar sesión, registrar, agregar productos en el carrito y al eliminarlos.

## Captura

![image](https://github.com/Lauty10/FrondFinal/assets/83432755/67af83e7-1b1e-4ed8-a8ae-4e18311dbb4a)

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by Lauty10** [comment]
https://github.com/Lauty10/FrondFinal/commit/d916f5a4210ea8899a0c837d48848447998818f9

**Comment by castromaciel** [comment]
Se valida la solución del issue!
