### ISSUE TITLE
Admin - Desaparecen las opciones del navbar

### ISSUE THREAD

**Issue by castromaciel** [Lauty10/FrondFinal#24]
## Proceso

1. Iniciar sesión como Admin.
2. Dirigirse a la página de inicio o sobre mi.

## Resultado esperado

Se esperaba que los ítems del nav permanezcan aunque se navegue por diferentes páginas.

## Resultado actual

Actualmente los items del nav desaparecen al cambiar de página.

## Captura

https://github.com/Lauty10/FrondFinal/assets/83432755/4a3f494a-3c41-4211-8b54-69eaf0b9003f

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by Lauty10** [comment]
https://github.com/Lauty10/FrondFinal/commit/6b254cc61194adf0c5b71304abf33a49d2adfdf9

**Comment by castromaciel** [comment]
Se valida la solución del issue!
